epumanagement:
  service_name: epu_management_service
  persistence_type: memory
  provisioner_topic: provisioner
  initial_epus: {}
  needy_default_iaas_site: site-1
  needy_default_iaas_allocation: t1.micro
  provisioner_vars: {}
