highavailability:
  service_name: highavailability
  processdispatchers: [processdispatcher,]
  policy:
    interval: 5
    name: npreserving
    parameters:
      preserve_n: 1
  process_spec:
    run_type: supd
    parameters: 
      exec: true
      argv: []
