server:
  amqp:
    host: localhost
    port: 5672
    username: guest
    password: guest
    vhost: /
    heartbeat: 30
logging:
  version: 1
  formatters:
    brief:
      format: '%(levelname)-8s %(message)s'
    default:
      format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'

  handlers:
    console:
      class: logging.StreamHandler
      formatter: brief
      level: DEBUG
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: default
      level: DEBUG
      filename: logs/logfile.txt
      maxBytes: 1024
      backupCount: 3
  loggers:
    epu:
      handlers: [console]
      level: DEBUG
      propagate: True
  root:
    handlers: [console]
    level: DEBUG
