context:
  uri: https://nimbus.ci.uchicago.edu:8888/ContextBroker/ctx/
  key: F22x3AWAq6T2I7789RePQ
  secret: Vaa6v67hBfXfSEpJsVac6sBKNVBEwkJ37jboZAHH1W
sites:
  ec2-west:
    driver_class: libcloud.drivers.ec2.EC2USWestNodeDriver
    driver_kwargs:
      key: AKIAJWAN7GHOKK6AKUUA
      secret: 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
